package com.objects.marketbridge.order.mock;

import com.objects.marketbridge.order.domain.OrderCancelReturn;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

@Getter
public class BaseFakeOrderCancelReturnRepository {

    @Getter
    private static final BaseFakeOrderCancelReturnRepository instance = new BaseFakeOrderCancelReturnRepository();

    private Long autoGeneratedId = 0L;
    private List<OrderCancelReturn> data = new ArrayList<>();

    protected Long increaseId() {
        return ++autoGeneratedId;
    }

    public void clear() {
        autoGeneratedId = 0L;
        data.clear();
    }
}
