DROP TABLE IF EXISTS member;

DROP TABLE IF EXISTS seller;

DROP TABLE IF EXISTS address;

DROP TABLE IF EXISTS social_credential;

DROP TABLE IF EXISTS category;

DROP TABLE IF EXISTS product;

DROP TABLE IF EXISTS reward_policy;

DROP TABLE IF EXISTS seller_product;

DROP TABLE IF EXISTS product_image;

DROP TABLE IF EXISTS image;

DROP TABLE IF EXISTS option_category;

DROP TABLE IF EXISTS prod_option;

DROP TABLE IF EXISTS tag;

DROP TABLE IF EXISTS prod_tag;

DROP TABLE IF EXISTS stock;

DROP TABLE IF EXISTS status_code;

DROP TABLE IF EXISTS prod_order;

DROP TABLE IF EXISTS prod_order_detail;

DROP TABLE IF EXISTS payment;

DROP TABLE IF EXISTS review;

DROP TABLE IF EXISTS review_image;

DROP TABLE IF EXISTS review_survey;

DROP TABLE IF EXISTS review_survey_category;

DROP TABLE IF EXISTS survey_content;

DROP TABLE IF EXISTS board;

DROP TABLE IF EXISTS qna;

DROP TABLE IF EXISTS help_desk;

DROP TABLE IF EXISTS delivery;

DROP TABLE IF EXISTS estimated_time;

DROP TABLE IF EXISTS coupon_budget;

DROP TABLE IF EXISTS coupon;

DROP TABLE IF EXISTS point;

DROP TABLE IF EXISTS admin;

DROP TABLE IF EXISTS cart;

DROP TABLE IF EXISTS wishlist;

DROP TABLE IF EXISTS payment_log;

DROP TABLE IF EXISTS prod_subs;

DROP TABLE IF EXISTS warehouse;

DROP TABLE IF EXISTS cancel_payment;

DROP TABLE IF EXISTS reward;

DROP TABLE IF EXISTS member_coupon;




