package com.objects.marketbridge.domains.order.mock;

import com.objects.marketbridge.domains.product.domain.Product;
import com.objects.marketbridge.domains.product.service.port.ProductCustomRepository;
import com.objects.marketbridge.domains.product.service.port.ProductRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeProductRepository implements ProductRepository , ProductCustomRepository {

    private Long autoGeneratedId = 0L;
    private List<Product> data = new ArrayList<>();

    @Override
    public Product findById(Long id) {
        return null;
    }

    @Override
    public Product saveAndFlush(Product product) {
        return null;
    }

    @Override
    public List<Product> findAllById(List<Long> ids) {
        return null;
    }

    @Override
    public List<Product> findByName(String name) {
        return null;
    }

    @Override
    public void deleteAllInBatch() {
        autoGeneratedId = 0L;
        data.clear();
    }

    @Override
    public Product save(Product product) {
        if (product.getId() == null || product.getId() == 0) {
            ReflectionTestUtils.setField(product, "id", ++autoGeneratedId, Long.class);
            data.add(product);
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), product.getId()));
            data.add(product);
        }
        return product;
    }

    @Override
    public List<Product> findAll() {
        return null;
    }

    @Override
    public void saveAll(List<Product> products) {
        for (Product p: products) {
            save(p);
        }
    }

    @Override
    public void delete(Product product) {

    }

    @Override
    public Page<Product> findAllByCategoryId(Pageable pageable, Long categoryId) {
        return null;
    }

    @Override
    public Product findByProductNo(String productNo) {
        return null;
    }

    @Override
    public Product findByIdwithCategory(Long id) {
        return null;
    }

    @Override
    public List<Product> findAllByProductNoLikeAndProductId(String productNo, Long productId) {
        List<Product> result = new ArrayList<>();
        for (Product product : data) {
            if (product.getId() != productId &&
                product.getProductNo().split(" - ")[0].equals(productNo)){
                result.add(product);
            }
        }
        return result;
    }
}
