package com.objects.marketbridge.mock;

import com.objects.marketbridge.order.domain.Order;

import java.util.ArrayList;
import java.util.List;

public class BaseFakeOrderRepository {

    private static final BaseFakeOrderRepository instance = new BaseFakeOrderRepository();

    protected Long autoGeneratedId = 0L;
    protected List<Order> data = new ArrayList<>();

    protected static BaseFakeOrderRepository getInstance() {
        return instance;
    }
}
