package com.objects.marketbridge.domains.coupon.mock;

import com.objects.marketbridge.domains.coupon.domain.Coupon;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class BaseFakeCouponRepository {
    @Getter
    private static final BaseFakeCouponRepository instance = new BaseFakeCouponRepository();

    private Long autoGeneratedId = 0L;
    private final List<Coupon> data = new ArrayList<>();

    protected Long increaseId() {
        return ++autoGeneratedId;
    }

    public void clear() {
        autoGeneratedId = 0L;
        data.clear();
    }
}
