package com.objects.marketbridge.domains.product.mock;

import com.objects.marketbridge.domains.product.domain.ProductGroup;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

@Getter
public class BaseFakeProductGroupRepository {
    @Getter
    private static final BaseFakeProductGroupRepository instance = new BaseFakeProductGroupRepository();

    private Long autoGeneratedId = 0L;
    private List<ProductGroup> data = new ArrayList<>();

    protected Long increaseId() {
        return ++autoGeneratedId;
    }

    public void clear() {
        autoGeneratedId = 0L;
        data.clear();
    }
}
