package com.objects.marketbridge.domains.cart.mock;

import com.objects.marketbridge.domains.cart.domain.Cart;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

@Getter
public class BaseFakeCartRepository {
    @Getter
    private static final BaseFakeCartRepository instance = new BaseFakeCartRepository();

    private Long autoGeneratedId = 0L;
    private List<Cart> data = new ArrayList<>();

    protected Long increaseId() {
        return ++autoGeneratedId;
    }

    public void clear() {
        autoGeneratedId = 0L;
        data.clear();
    }
}
