name: MarketBridge CI/CD

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/Setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Add to application.yml
        run: |
          cd ./src/main/resources
          cat << EOF >> ./application.yml

          ${{secrets.KAKAO_REQ_HOST}}
          
          ${{secrets.JWT_SECRET}}
          EOF

        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --platform linux/arm64/v8 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:0.1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:0.1

      - name: execute remote ssh & deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
#          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:0.1
            cd ~
            docker-compose up -d
            docker image prune -f
            docker ps -a
